tokens_per_step: 524_288
warmup_tokens: 5000
optim: adamw_torch_fused
lr: 3.0e-4
weight_decay: 0.01
adam_betas: (0.9, 0.95)
max_grad_norm: 1.0
gradient_accum: 1
lr_scheduler_type: cosine_with_min_lr
min_lr_rate: 0.1
gradient_checkpointing: false
ddp_find_unused_parameters: false

logging_steps: 50
save_total_limit: 4

dataloader_num_workers: 16
dataloader_pin_memory: true
dataloader_persistent_workers: true
